id: IF7B71848
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:38:20.698199'
last_modified: '2022-06-11T13:38:20.698205'
parser: null
source_metadata:
  title: Nāgārjuna
  language: pt
  description: 'Texts by and about the great Indian philosopher-saint Ārya Nāgārjuna
    (''phags pa klu sgrub, c.150 – c.250 CE), known to Tibetans as the founder of
    the tradition of Profound View (zab mo lta ba):'
  volume:
    f6BCC:
      title: Commentary on the Noble Essence of the Dharmadhātu
      base_file: f6BCC.txt
      order: 1
      parent: Dependent Origination
    f0B79:
      title: Verses on the Heart of Dependent Origination
      base_file: f0B79.txt
      order: 2
      parent: Dependent Origination
    fF678:
      title: In Praise of the Twelve Deeds of the Buddha
      base_file: fF678.txt
      order: 3
      parent: Praise
    fEED9:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      base_file: fEED9.txt
      order: 4
      parent: Praise
    f5AAB:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      base_file: f5AAB.txt
      order: 5
      parent: Praise
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
